# Test libs

In [1]:
import numpy as np

In [3]:
# creat array , matrix
a = np.array([1, 2, 3, 4])

In [4]:
a

array([1, 2, 3, 4])

In [8]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [9]:
#shape
print(a.shape, b.shape)

(4,) (2, 2)


In [10]:
# reshape
c = a.reshape((4, 1))

In [11]:
c

array([[1],
       [2],
       [3],
       [4]])

In [12]:
c.shape

(4, 1)

In [16]:
d = a.reshape((2, 2, -1))
d.shape

(2, 2, 1)

In [ ]:
# concatenate
# L1 = L2
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5])

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
c

array([5, 7, 9])

In [23]:
c = a * b
c

array([ 4, 10, 18])