# Numpy Document

In [11]:
import numpy as np

### create array and matrix

In [12]:
# name = np.array([val])

myMat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myMat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
a = np.array([1,2,3,4,5,6,7,8,9])

b = np.array([[1,2,3,4],[6,7,8,9]])


print(b)

[[1 2 3 4]
 [6 7 8 9]]


### shape cells

In [14]:
#برای فهمیدن تعداد سطر و ستون ها

print(np.shape(a))
print(np.shape(b))
# OR
print(b.shape, a.shape)

(9,)
(2, 4)
(2, 4) (9,)


### reshape

In [15]:
#listname.reshape(new_size)
c = np.array([1,2,3,4,5,6,7,8,9])
print(c)

print(np.shape(c))

print(c.reshape(9,1))

print(np.shape(c))


[1 2 3 4 5 6 7 8 9]
(9,)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9,)


In [16]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

b = a.reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


#### -1 in reshape

In [17]:
#اگر مقدار رو نمیدونستیم منفی یک میزاریم خودش میسازه

c = a.reshape(5,-1)
print(c)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### Concatenate

In [18]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
b = np.array([15,16,17,18,19,20,21,22,23,24,25])


c = np.concatenate((a,b))
print(c)

# حالا میخام یه ماتریس دو ستونه بسازم
d = c.reshape(-1,2)
print(d)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 15 16 17 18 19 20 21 22 23
 24 25]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]]


### brodcasting


In [19]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
b = np.array([16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])

c = a + b
print(c)

d = a - b
print(d)

e = a +100
print(e)

f = a / 2
print(f)

g = a % 2
print(g)





[17 19 21 23 25 27 29 31 33 35 37 39 41 43 45]
[-15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15 -15]
[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5]
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [20]:


import numpy as reza
a = reza.array([1, 2])
print(a)


[1 2]
