# Test libs

In [3]:
import numpy as np

In [4]:
# creat array , matrix
a = np.array([1, 2, 3, 4])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [7]:
#shape
print(a.shape, b.shape)

(4,) (2, 2)


In [8]:
# reshape
c = a.reshape((4, 1))

In [9]:
c

array([[1],
       [2],
       [3],
       [4]])

In [10]:
c.shape

(4, 1)

In [11]:
d = a.reshape((2, 2, -1))
d.shape

(2, 2, 1)

In [12]:
# concatenate افقی 
# L1 = L2
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5])

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
c

array([5, 7, 9])

In [14]:
c = a * b
c

array([ 4, 10, 18])

In [15]:

c = np.array([10])
d = a + b
d


array([5, 7, 9])

In [16]:
d = a + c

In [17]:
d 

array([11, 12, 13])

In [18]:
e = d + 5
e

array([16, 17, 18])

In [19]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

In [20]:
a.shape

(14,)

In [21]:
# در نامپای اندیس گذاری از صفر استارت میخوره

In [22]:
b = a[2:7]
b

array([3, 4, 5, 6, 7])

In [23]:
b = a[0:9]
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#طول گام 
b = a[1:10:2]
b

array([ 2,  4,  6,  8, 10])

In [25]:
b

array([ 2,  4,  6,  8, 10])

In [26]:
#اینجا a های بزرگتر از 3 رو میده بیرون
c = a[a>3]
c

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
#استفاده از توابع ریاضی
sum_a = np.sum(a)
sum_a

np.int64(105)

In [28]:
#محاسبه مجموع تمامی المانهای بردار
np.sum(list)

list

In [29]:
#ماکزیمم المان 
max_a = np.max(a)
max_a

np.int64(14)

In [30]:
import numpy as np
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])



In [31]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
sum_a = np.sum(a)

In [33]:
sum_a

np.int64(45)

In [34]:
#min array
min_a = np.min(a)

In [35]:
min_a

np.int64(1)

In [36]:
#sort list
a = np.array = ([4,5,10,7,6,3,1])
b = np.sort(a)
b

array([ 1,  3,  4,  5,  6,  7, 10])

In [67]:
#normalizetion
mean_a = np.mean((a))
mean_a


np.float64(5.142857142857143)

In [ ]:
#انحراف معیار
std_a = np.std(a)
std_a

np.float64(2.695423180587601)

In [68]:
norm_a = (a - mean_a)/std_a
norm_a

array([-0.42399915, -0.05299989,  1.8019964 ,  0.68899862,  0.31799936,
       -0.79499841, -1.53699693])

In [69]:
np.mean(norm_a)

np.float64(-1.9032394707859825e-16)

In [ ]:
'''
تمرین ۱: جمع و میانگین
یک آرایه a با اعداد ۱۰ تا ۳۰ بساز.
جمع کل عناصر و میانگین آن‌ها را محاسبه کن.

'''

a = np.arange(10,31)
sum_a = np.sum(a)
sum_a

np.int64(420)

In [73]:
mean_a = np.mean(a)
mean_a

np.float64(20.0)

In [ ]:
'''
تمرین ۲: vstack و hstack

دو آرایه ۱ بعدی a = [1,2,3] و b = [4,5,6] بساز.

آن‌ها را عمودی روی هم بچین و افقی کنار هم .

خروجی هر حالت را چاپ کن.

'''
import numpy as np 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v_stack = np.vstack((a, b))
print(v_stack)

h_stack = np.hstack((a, b))
print(h_stack)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [2]:
print("Hello world")

Hello world


In [1]:
s = 2
type(s)

int

In [3]:
b = 3.43
type(b)

float

In [5]:
c = True 
type(c)

bool

### type casting

In [8]:
a = 34
b = 234.42
c = False 
type(a), type(b), type(c)

(int, float, bool)

In [9]:
f = a + b
f

268.41999999999996

### 2.explicit
-int
-float
-str
-bool

In [10]:
a = 3.343434
int(a)

3

In [11]:
float(a)

3.343434

In [13]:
b = False
int(b) #true=> 1 false=>0 

0

In [14]:
v = 24.23424
bool(v)

True

In [ ]:
d = 2342234.23
round(d) 

2342234

In [18]:
b = 3
a = -34.33
c = True
float(b), float(a), float(c)

(3.0, -34.33, 1.0)

In [19]:
a = 3
str(a)

'3'

In [21]:
a = 3
b = 324.24
c = "v"
bool(a), bool(b), bool(c)

(True, True, True)

In [22]:
a = ""
bool(a)

False

In [5]:

print("hello")

hello


In [1]:
s = "true"
type(s)

str

In [1]:
print('hello word')

hello word


In [1]:
x = 23 
float(x)

23.0

In [1]:
print("hello")

hello
