# Test libs

In [11]:
import numpy as np

In [12]:
# creat array , matrix
a = np.array([1, 2, 3, 4])

In [13]:
a

array([1, 2, 3, 4])

In [14]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [15]:
#shape
print(a.shape, b.shape)

(4,) (2, 2)


In [16]:
# reshape
c = a.reshape((4, 1))

In [17]:
c

array([[1],
       [2],
       [3],
       [4]])

In [18]:
c.shape

(4, 1)

In [19]:
d = a.reshape((2, 2, -1))
d.shape

(2, 2, 1)

In [20]:
# concatenate افقی 
# L1 = L2
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.concatenate((a, b))
c

array([1, 2, 3, 4, 5])

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
c

array([5, 7, 9])

In [22]:
c = a * b
c

array([ 4, 10, 18])

In [23]:

c = np.array([10])
d = a + b
d


array([5, 7, 9])

In [24]:
d = a + c

In [25]:
d 

array([11, 12, 13])

In [26]:
e = d + 5
e

array([16, 17, 18])

In [27]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])

In [28]:
a.shape

(14,)

In [29]:
# در نامپای اندیس گذاری از صفر استارت میخوره

In [30]:
b = a[2:7]
b

array([3, 4, 5, 6, 7])

In [31]:
b = a[0:9]
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#طول گام 
b = a[1:10:2]
b

array([ 2,  4,  6,  8, 10])

In [33]:
b

array([ 2,  4,  6,  8, 10])

In [34]:
#اینجا a های بزرگتر از 3 رو میده بیرون
c = a[a>3]
c

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
#استفاده از توابع ریاضی
sum_a = np.sum(a)
sum_a

np.int64(105)

In [36]:
#محاسبه مجموع تمامی المانهای بردار
np.sum(list)

np.int64(234245)

In [37]:
#ماکزیمم المان 
max_a = np.max(a)
max_a

np.int64(14)

In [38]:
import numpy as np
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])



In [39]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
sum_a = np.sum(a)

In [41]:
sum_a

np.int64(45)

In [42]:
#min array
min_a = np.min(a)

In [43]:
min_a

np.int64(1)

In [44]:
#sort list
a = np.array = ([4,5,10,7,6,3,1])
b = np.sort(a)
b

array([ 1,  3,  4,  5,  6,  7, 10])

In [45]:
#normalizetion
mean_a = np.mean((a))
mean_a


np.float64(5.142857142857143)

In [46]:
#انحراف معیار
std_a = np.std(a)
std_a

np.float64(2.695423180587601)

In [47]:
norm_a = (a - mean_a)/std_a
norm_a

array([-0.42399915, -0.05299989,  1.8019964 ,  0.68899862,  0.31799936,
       -0.79499841, -1.53699693])

In [48]:
np.mean(norm_a)

np.float64(-1.9032394707859825e-16)

In [49]:
'''
تمرین ۱: جمع و میانگین
یک آرایه a با اعداد ۱۰ تا ۳۰ بساز.
جمع کل عناصر و میانگین آن‌ها را محاسبه کن.

'''

a = np.arange(10,31)
sum_a = np.sum(a)
sum_a

np.int64(420)

In [50]:
mean_a = np.mean(a)
mean_a

np.float64(20.0)

In [51]:
'''
تمرین ۲: vstack و hstack

دو آرایه ۱ بعدی a = [1,2,3] و b = [4,5,6] بساز.

آن‌ها را عمودی روی هم بچین و افقی کنار هم .

خروجی هر حالت را چاپ کن.

'''
import numpy as np 

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v_stack = np.vstack((a, b))
print(v_stack)

h_stack = np.hstack((a, b))
print(h_stack)

TypeError: 'list' object is not callable

In [ ]:
print("Hello world")

Hello world


In [ ]:
s = 2
type(s)

int

In [ ]:
b = 3.43
type(b)

float

In [ ]:
c = True 
type(c)

bool

### type casting

In [ ]:
a = 34
b = 234.42
c = False 
type(a), type(b), type(c)

(int, float, bool)

In [ ]:
f = a + b
f

268.41999999999996

### 2.explicit
-int
-float
-str
-bool

In [ ]:
a = 3.343434
int(a)

3

In [ ]:
float(a)

3.343434

In [ ]:
b = False
int(b) #true=> 1 false=>0 

0

In [ ]:
v = 24.23424
bool(v)

True

In [ ]:
d = 2342234.23
round(d) 

2342234

In [ ]:
b = 3
a = -34.33
c = True
float(b), float(a), float(c)

(3.0, -34.33, 1.0)

In [ ]:
a = 3
str(a)

'3'

In [ ]:
a = 3
b = 324.24
c = "v"
bool(a), bool(b), bool(c)

(True, True, True)

In [ ]:
a = ""
bool(a)

False

In [ ]:

print("hello")

hello


In [ ]:
s = "true"
type(s)

str

In [ ]:
print('hello word')

hello word


In [ ]:
x = 23 
float(x)

23.0

In [ ]:
print("hello")

hello


### Tuple

In [ ]:
lan = ("python", "c", "php")
type(lan)

tuple

In [ ]:
test = (1,2,3,4,5,6,7,8,9)
type(test)

tuple

In [ ]:
a = test[1:7:2]
a

(2, 4, 6)

In [ ]:
b = lan[0:3]
b

('python', 'c', 'php')

In [ ]:
names = 'ali', 'jack', 'reza'
names

('ali', 'jack', 'reza')

In [ ]:
type(names)

tuple

### Unpacking

In [ ]:
a = 1,2,3


In [ ]:
x, y, z = a

In [ ]:
y

2

### Edit

In [ ]:
a = 1,2,3
a[1] = 43


TypeError: 'tuple' object does not support item assignment

### List

In [ ]:
list = [1, 2, 3, 4, 5]
type(list)

list

In [ ]:
a = [1,3,4,56,3345,3535]
type(a)

list

In [ ]:
print(list[1])

2


In [ ]:
print(a[2])

4


### ادیت لیست 

In [ ]:
list[3] = 234234


In [ ]:
list

[1, 2, 3, 234234, 5]

In [ ]:
b = [1,2,2] #عدد مشابه مجازه

### append

به لیست یک دستور اضافه میکند

In [52]:
list

[1, 2, 3, 234234, 5]

In [54]:
list.append(5)
list

[1, 2, 3, 234234, 5, 5, 5]

In [6]:
list.append(4,45,545) #دقت شود 

TypeError: descriptor 'append' for 'list' objects doesn't apply to a 'int' object

### Rimove in list

In [58]:
a = ['s', 'sdf']
a.remove('s')
a

['sdf']

### Slice in list

In [3]:
a = [1,2.3,43,43,42,23,42,4,2,34,24,2,4,24]
b = a[1:5]
b

[2.3, 43, 43, 42]

### Cancatenation

In [5]:
a = [1,34,43]
b = [2,3,5,7]
c = a + b
c

[1, 34, 43, 2, 3, 5, 7]

In [8]:
v = [1,2,2,33,56,89]
g = v * 4
g

[1,
 2,
 2,
 33,
 56,
 89,
 1,
 2,
 2,
 33,
 56,
 89,
 1,
 2,
 2,
 33,
 56,
 89,
 1,
 2,
 2,
 33,
 56,
 89]

In [11]:
a = 'hello' #string is list
a[1:3]

'el'

### dictipnary

In [1]:
student = {

    'name': 'reza' , 
    'age' : 33, 
    'field' : 'cs'
}

In [2]:
type(student)

dict

In [3]:
car = {
    'brand' : 'bmw',
    'year' : '2021',
    'type' : 'sedan'
     
}

In [4]:
car

{'brand': 'bmw', 'year': '2021', 'type': 'sedan'}

### access

In [6]:
age = student['age']
age

33

In [7]:
student

{'name': 'reza', 'age': 33, 'field': 'cs'}

### add element

In [10]:
# Define student
student = {
    'name': 'reza',
    'age': 33,
    'field': 'cs'
}

# Add new key-value
student["dsds"] = "1000"

print(student)


{'name': 'reza', 'age': 33, 'field': 'cs', 'dsds': '1000'}


### methods

In [11]:
student.keys()

dict_keys(['name', 'age', 'field', 'dsds'])

In [12]:
student.values()

dict_values(['reza', 33, 'cs', '1000'])

In [13]:
student.items()

dict_items([('name', 'reza'), ('age', 33), ('field', 'cs'), ('dsds', '1000')])

### set

In [16]:
a = {1,2,3,4,4,5,6}
a #مقدار تکراری در ست وجود ندارد

{1, 2, 3, 4, 5, 6}

### add

In [17]:
a = {1,2,3}
a.add(4)
a

{1, 2, 3, 4}

In [19]:
a.add(3)
a

{1, 2, 3, 4}

### remove

In [20]:
a.remove(3)
a

{1, 2, 4}

### methods

In [22]:
a = {1,3,2,4}
b = {2,2,4,7}
a.union(b) #اجتماع

{1, 2, 3, 4, 7}

In [24]:
a.intersection(b) #اشتراک

{2, 4}

In [27]:
d = a.difference(b)
d

{1, 3}

In [29]:
b.difference(a)

{7}